name: Oppdater Oslo lufthavn-status

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: Oppdater Datawrapper-tabell
        env:
          DATAWRAPPER_API_TOKEN: ${{ secrets.DATAWRAPPER_API_TOKEN }}
          DATAWRAPPER_CHART_ID: ${{ secrets.DATAWRAPPER_CHART_ID }}
        run: python oslo_lufthavn_status.py
